// <auto-generated />
using Angular_HomePowerComsumption.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Angular_HomePowerComsumption.Migrations
{
    [DbContext(typeof(PowerDbContext))]
    [Migration("20191002005312_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Angular_HomePowerComsumption.Models.Appliance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatthourMeterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<int>("kwh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<float>("useHrPerMonth")
                        .HasColumnType("REAL");

                    b.Property<int>("watt")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("FloorId");

                    b.HasIndex("WatthourMeterId");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("Angular_HomePowerComsumption.Models.Floor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("Angular_HomePowerComsumption.Models.WatthourMeter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("kwh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("WatthourMeters");
                });

            modelBuilder.Entity("Angular_HomePowerComsumption.Models.Appliance", b =>
                {
                    b.HasOne("Angular_HomePowerComsumption.Models.Floor", "Floor")
                        .WithMany("Appliances")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Angular_HomePowerComsumption.Models.WatthourMeter", "WatthourMeter")
                        .WithMany("Appliances")
                        .HasForeignKey("WatthourMeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
